{
  "errors": [
    {
      "filename": "...]]",
      "reason": "No such file or directory"
    },
    {
      "filename": "[auth.py",
      "reason": "No such file or directory"
    },
    {
      "filename": "[targets",
      "reason": "No such file or directory"
    }
  ],
  "generated_at": "2021-08-18T15:11:24Z",
  "metrics": {
    "_totals": {
      "CONFIDENCE.HIGH": 0,
      "CONFIDENCE.LOW": 0,
      "CONFIDENCE.MEDIUM": 0,
      "CONFIDENCE.UNDEFINED": 0,
      "SEVERITY.HIGH": 0,
      "SEVERITY.LOW": 0,
      "SEVERITY.MEDIUM": 0,
      "SEVERITY.UNDEFINED": 0,
      "loc": 0,
      "nosec": 0
    }
  },
  "results": []
}